pivot table

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('names.csv',header=0,index_col=0,parse_dates=['Dob'],date_format='%Y-%m-%d')
now = pd.Timestamp.now()
df['Age'] = ((now.year - df["Dob"].dt.year))
df = df.assign(Post = np.where(df['Age']<=25,'Junior',np.where(df['Age']<=35,'Senior',np.where(df['Age']>35,'Manager','Intern'))))
df.dtypes
df.to_csv('names.csv',header=True,index=True)

In [ ]:
df = pd.read_csv('names.csv',header=0,index_col=0,parse_dates=['Dob'],dayfirst=False)
df.drop('Post',axis=1,inplace=True)
#df.assign(pd.cut(df['Age'],bins=[0,25,35,float('inf'),labels=['Junior,Senior,Man']]))
df.loc[df['Name']=='Michael','Age'] = 18
df['Post'] = pd.cut(df['Age'],bins=[0,25,35,float('inf')],labels=['Junior','Senior','Manager'])
df['Post'] = df['Post'].cat.add_categories(['Intern']).fillna('Intern') # it is used to add a new category 
df.to_csv('names.csv',header=True,index=True)

In [ ]:
df['Age'].rolling(window=3).mean() # moving average

In [ ]:
df['Post'] = df['Post'].cat.reorder_categories(['Intern','Junior', 'Senior', 'Manager',])
condition = [df['Post']=='Intern',df['Post']=='Junior',df['Post']=='Senior',df['Post']=='Manager']
salary = [20000,30000,40000,50000]
df['Salary'] = np.select(condition,salary)
df.to_csv('names.csv',header=True,index = True)

In [ ]:
df = pd.read_csv('names.csv',index_col = 0 , header=0)
df['cumulative_salary'] = df['Salary'].cumsum()
print(df)
df.pivot_table(index='Post',columns='Department',values='Salary',aggfunc='sum').fillna(0)

In [ ]:
pd.crosstab( df["Department"],df["Post"]) # used to find the frequency of each category

In [ ]:
pd.melt(df, id_vars=["Id"], value_vars=["Salary"]) # id_vars is the list of columns to be used as the index value_vars is the list of columns to be used as the value with thir respective column name to

In [ ]:
data = {
    'Id' : [1,2,3,4,5],
    'Name' : ['John', 'Mary', 'Alex', 'Peter', 'Anna'],
    'Age' : [20, 25, 30, 35, 40],
    'Salary' : [1200, 2500, 2800, 3600, 4750],
    'Department' : ['HR', 'IT', 'HR', 'IT', 'HR']
}
df = pd.DataFrame(data)
df.set_index('Id',inplace=True)

In [ ]:
df['Rank'] = df.groupby('Department')['Salary'].rank(method='first',ascending=True).astype('Int64')
print(df)
df.drop('Rank', axis=1, inplace=True)

In [ ]:
df['Dept_wise_Sal_Rank'] = df.groupby('Department')['Salary'].rank(method='first', ascending=False).astype(int)
df['Salary_Rank'] = df['Salary'].rank(method='first', ascending=False).astype(int)
df

In [ ]:
df.stack() # stack the columns into row based on the index values
df.unstack() # unstack the columns into rows  based on the column name and the value under the column into rows

In [97]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D', 'E'],
    'Dept': ['IT', 'IT', 'HR', 'HR', 'HR'],
    'Salary': [50, 65, 55, 55, 65]
})
df['Rank'] = df.groupby('Dept')['Salary'].rank(method='first', ascending=False).astype(int)
print(df)
df.sort_values(by=['Dept','Rank'], ascending=[False,True])

  Name Dept  Salary  Rank
0    A   IT      50     2
1    B   IT      65     1
2    C   HR      55     2
3    D   HR      55     3
4    E   HR      65     1

  Name Dept  Salary  Rank
1    B   IT      65     1
0    A   IT      50     2
4    E   HR      65     1
2    C   HR      55     2
3    D   HR      55     3

In [98]:
df['Dept_Avg'] = df.groupby('Dept')['Salary'].transform('mean').astype('int')
df['Dept'] = df['Dept'].astype('category')
df

  Name Dept  Salary  Rank  Dept_Avg
0    A   IT      50     2        57
1    B   IT      65     1        57
2    C   HR      55     2        58
3    D   HR      55     3        58
4    E   HR      65     1        58