pivot table

In [3]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv('names.csv',header=0,index_col=0,parse_dates=['Dob'],date_format='%Y-%m-%d')
now = pd.Timestamp.now()
df['Age'] = ((now.year - df["Dob"].dt.year))
df = df.assign(Post = np.where(df['Age']<=25,'Junior',np.where(df['Age']<=35,'Senior',np.where(df['Age']>35,'Manager','Intern'))))
df.dtypes
df.to_csv('names.csv',header=True,index=True)

In [36]:
df = pd.read_csv('names.csv',header=0,index_col=0,parse_dates=['Dob'],dayfirst=False)
df.drop('Post',axis=1,inplace=True)
#df.assign(pd.cut(df['Age'],bins=[0,25,35,float('inf'),labels=['Junior,Senior,Man']]))
df.loc[df['Name']=='Michael','Age'] = 18
df['Post'] = pd.cut(df['Age'],bins=[0,25,35,float('inf')],labels=['Junior','Senior','Manager'])
df['Post'] = df['Post'].cat.add_categories(['Intern']).fillna('Intern') # it is used to add a new category 
df.to_csv('names.csv',header=True,index=True)

In [ ]:
df['Age'].rolling(window=3).mean() # moving average

       Name  Age        Dob  Marks  Height
Id
1      Riya   21 2005-05-23     85     170
2      Anna   27 1999-08-15     92     165
3     Peter   38 1988-12-10     78     180
4     Linda   35 1991-03-05     95     160
5       Tom   33 1993-11-12     88     175
6      Sara   26 2000-01-30     90     168
7     David   34 1992-07-20     82     172
8     Emily   31 1995-09-18     89     163
9   Michael   18 1983-02-25     91     185
10   Sophia   29 1997-06-14     87     167

In [ ]:
df['Post'] = df['Post'].cat.reorder_categories(['Intern','Junior', 'Senior', 'Manager',])
condition = [df['Post']=='Intern',df['Post']=='Junior',df['Post']=='Senior',df['Post']=='Manager']
salary = [20000,30000,40000,50000]
df['Salary'] = np.select(condition,salary)
df.to_csv('names.csv',header=True,index = True)

In [118]:
df = pd.read_csv('names.csv',index_col = 0 , header=0)
df['cumulative_salary'] = df['Salary'].cumsum()
print(df)
df.pivot_table(columns='Department',values='cumulative_salary',aggfunc='sum')

       Name  Age         Dob  Marks  Height     Post  Salary Department  \
Id
1      Riya   21  2005-05-23     85     170   Junior   30000         IT
2      Anna   27  1999-08-15     92     165   Senior   40000         HR
3     Peter   38  1988-12-10     78     180  Manager   50000         IT
4     Linda   35  1991-03-05     95     160   Senior   40000    Finance
5       Tom   33  1993-11-12     88     175   Senior   40000         HR
6      Sara   26  2000-01-30     90     168   Senior   40000         IT
7     David   34  1992-07-20     82     172   Senior   40000    Finance
8     Emily   31  1995-09-18     89     163   Senior   40000         IT
9   Michael   18  1983-02-25     91     185   Junior   30000         HR
10   Sophia   29  1997-06-14     87     167   Senior   40000    Finance

    cumulative_salary
Id
1               30000
2               70000
3              120000
4              160000
5              200000
6              240000
7              280000
8              320000
9              350000
10             390000

Department         Finance      HR      IT
cumulative_salary   830000  620000  710000