In [1]:
import pandas as pd
import numpy as np

#group by

In [3]:
df = pd.read_csv('employee.csv',header=0,index_col=0,skipinitialspace=True)
print(df)

        name  age           city  gender  salary  hike   bonus
id
1       Riya   28       New York  Female   12000   1.3  1200.0
2        Ram   29         London    Male   12000   1.3  1200.0
3      Shree   45          Paris  Female   13000   1.4  1300.0
4     Sushma   15          Tokyo  Female   11000   1.2  1100.0
5       John   22         Sydney    Male   12000   1.3  1200.0
6   Shreeram   27         Mumbai    Male   11237   1.2  1123.0
7       Amit   31         Berlin    Male   15000   1.5  1500.0
8      Priya   26        Toronto  Female   12500   1.3  1250.0
9      Karan   33          Dubai    Male   14000   1.4  1400.0
10      Neha   24      Singapore  Female   11800   1.2  1180.0
11     David   38        Chicago    Male   16000   1.6  1600.0
12    Sophia   30      Melbourne  Female   13500   1.4  1350.0
13     Arjun   41          Delhi    Male   17000   1.7  1700.0
14     Meera   36      Bangalore  Female   15500   1.5  1550.0
15     Rohit   23           Pune    Male   11500   1.2  1150.0
16    Anjali   34        Chennai  Female   14500   1.4  1450.0
17   Michael   40    Los Angeles    Male   18000   1.8  1800.0
18      Emma   27  San Francisco  Female   15000   1.5  1500.0
19    Vikram   32      Hyderabad    Male   14200   1.4  1420.0
20      Lisa   29      Amsterdam  Female   13800   1.3  1380.0

df.index.name = 'id' to give the default index name

In [ ]:
col = list(df.columns)
#df.drop('dept',axis = 1,inplace=True)
df.insert(col.index('gender')+1,'dept',np.where(df['salary']==12000,'IT',np.where(df['salary']>12000,'Finance','HR')))
print(df)

In [ ]:
'''print(df.groupby('dept')['salary'].sum())
print(df.groupby('dept')['salary'].mean())
print(df.groupby('dept')['salary'].count())
print(df.groupby('dept')['salary'].min())
print(df.groupby('dept')['salary'].max())'''
print(df.groupby('dept').agg({'salary':{'sum','mean','count','min','max'}}))
print(df.groupby('dept').agg({'salary':'sum','bonus':'sum','age':'mean'}).astype(int))
print(df.groupby('dept')['salary'].agg(['sum','mean','count','min','max']).astype(int))
print(df.groupby('dept')['salary'].agg(avg_sal=('mean'),total_sal='sum',total_emp=('count')).astype(int))

In [ ]:
# transform is used to maintain the shape of the datafram even if we apply groupby it will calculate the groupby object then transform the shape back 
df['dept_avg'] = df.groupby('dept')['salary'].transform('mean')
df['diff'] = df['salary'] - df['dept_avg']
print(df)

In [ ]:
df.drop(['diff','dept_avg'],axis=1,inplace=True)

In [ ]:
df.groupby('dept').filter(lambda x : x['salary'].mean() >= 12000)

In [ ]:
data = pd.read_csv('employee.csv', header=0, index_col=0)
#print(data)
col = list(data.columns)
data.insert(col.index('age')+1,'position',
            np.where(data['age']<20,'intern',
            np.where(data['age']<30,'jr dev',
            np.where(data['age']<40,'sr dev','manager'))))
print(data)

In [50]:
df2 = pd.read_csv('names2.csv',header=0,index_col=0)
print(df2)
df1 = pd.read_csv('names.csv',header=0,index_col=0)
print(df1)

    std     Name
Id
1     6     John
2     7     Anna
3     8    Peter
4     9    Linda
5     5      Tom
6     4     Sara
7     7    David
8     8    Emily
9     9  Michael
10    7   Sophia
       Name  Age         Dob  Marks  Height
Id
1      John   18  23-05-2005     85     170
2      Anna   24  15-08-1999     92     165
3     Peter   35  10-12-1988     78     180
4     Linda   32  05-03-1991     95     160
5       Tom   28  12-11-1993     88     175
6      Sara   22  30-01-2000     90     168
7     David   30  20-07-1992     82     172
8     Emily   27  18-09-1995     89     163
9   Michael   40  25-02-1983     91     185
10   Sophia   26  14-06-1997     87     167

In [52]:
pd.merge(df2,df1,on='Id',how='right')
pd.merge(df2,df1,on='Id',how='left')
pd.merge(df2,df1,left_on = 'Id',right_on='Id')
pd.merge(df1,df2,left_on=['Id','Name'],right_on=['Id','Name'])
df1

       Name  Age         Dob  Marks  Height
Id
1      John   18  23-05-2005     85     170
2      Anna   24  15-08-1999     92     165
3     Peter   35  10-12-1988     78     180
4     Linda   32  05-03-1991     95     160
5       Tom   28  12-11-1993     88     175
6      Sara   22  30-01-2000     90     168
7     David   30  20-07-1992     82     172
8     Emily   27  18-09-1995     89     163
9   Michael   40  25-02-1983     91     185
10   Sophia   26  14-06-1997     87     167

In [ ]:
#df1.rename(columns = {'name':'Name'},inplace=True)
data = pd.DataFrame({
                    'id':[1,2,3,4,5],
                    'name': ['Alice', 'Bob', 'Charlie', 'Dennis', 'Edith'],
                    'age': [20, 25, 30, 35, 40],
                    'height': [1.76, 1.67, 1.58, 1.43, 1.50],
                    'weight': [69, 62, 58, 54, 50]})
# first method 
data.index = range(1,len(data)+1)
data.index.name = 'id'
# second method 
data['Sr.no'] = [i for i in range(1,len(data)+1)]
data.index = data['Sr.no']
# third method 
data.set_index('Sr.no', inplace=True)
# drop
data.reset_index(inplace=True,drop=True)
print(data)
# date and time 
now = pd.Timestamp.now()
df = pd.read_csv('names.csv',index_col=0,header=0,parse_dates=['Dob'], date_format="%d-%m-%Y") 
#df.drop('Age by Months',axis=1,inplace=True)
print(df['Dob'].dtype)
col = list(df.columns)
df.drop('Age',axis=1,inplace=True)
df.insert(col.index('Dob'),'Age',((now.year - df["Dob"].dt.year)))
print(df)

   id     name  age  height  weight
0   1    Alice   20    1.76      69
1   2      Bob   25    1.67      62
2   3  Charlie   30    1.58      58
3   4   Dennis   35    1.43      54
4   5    Edith   40    1.50      50
datetime64[us]
       Name        Dob  Age  Marks  Height
Id
1      John 2005-05-23   21     85     170
2      Anna 1999-08-15   27     92     165
3     Peter 1988-12-10   38     78     180
4     Linda 1991-03-05   35     95     160
5       Tom 1993-11-12   33     88     175
6      Sara 2000-01-30   26     90     168
7     David 1992-07-20   34     82     172
8     Emily 1995-09-18   31     89     163
9   Michael 1983-02-25   43     91     185
10   Sophia 1997-06-14   29     87     167

In [6]:
df.T.drop_duplicates(keep='first') #trying to drop the columns different name but same values

id,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
name,Riya,Ram,Shree,Sushma,John,Shreeram,Amit,Priya,Karan,Neha,David,Sophia,Arjun,Meera,Rohit,Anjali,Michael,Emma,Vikram,Lisa
age,28,29,45,15,22,27,31,26,33,24,38,30,41,36,23,34,40,27,32,29
city,New York,London,Paris,Tokyo,Sydney,Mumbai,Berlin,Toronto,Dubai,Singapore,Chicago,Melbourne,Delhi,Bangalore,Pune,Chennai,Los Angeles,San Francisco,Hyderabad,Amsterdam
gender,Female,Male,Female,Female,Male,Male,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female
salary,12000,12000,13000,11000,12000,11237,15000,12500,14000,11800,16000,13500,17000,15500,11500,14500,18000,15000,14200,13800
hike,1.3,1.3,1.4,1.2,1.3,1.2,1.5,1.3,1.4,1.2,1.6,1.4,1.7,1.5,1.2,1.4,1.8,1.5,1.4,1.3
bonus,1200.0,1200.0,1300.0,1100.0,1200.0,1123.0,1500.0,1250.0,1400.0,1180.0,1600.0,1350.0,1700.0,1550.0,1150.0,1450.0,1800.0,1500.0,1420.0,1380.0

In [9]:
df1 = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Hank'],
                   'Department': ['HR', 'Tech', 'Tech', 'HR', 'Finance', 'Finance', 'Tech', 'HR'],
                   'Salary': [55000, 82000, 91000, 60000, 73000, 68000, 95000, 52000]})
df2 = pd.DataFrame({'Years': [3, 5, 7, 2, 4, 6, 8, 1],
                   'Rating': [4.1, 3.8, 4.5, np.nan, 4.0, 3.5, 4.7, np.nan],
                   'City': ['NYC', 'LA', 'NYC', 'Chicago', 'LA', 'NYC', 'Chicago', 'LA'],
                   'Gender': ['F', 'M', 'M', 'F', 'F', 'M', 'F', 'M']})

In [ ]:
# stacking 
df3 = pd.concat([df1,df2],axis=1) # axis = 1 for columns to it concat the them horizontally
print(df3)
df3 = pd.concat([df1,df2],axis=0) # axis = 0 for rows to it concat the them vertically
print(df3)

      Name Department  Salary  Years  Rating     City Gender
0    Alice         HR   55000      3     4.1      NYC      F
1      Bob       Tech   82000      5     3.8       LA      M
2  Charlie       Tech   91000      7     4.5      NYC      M
3    Diana         HR   60000      2     NaN  Chicago      F
4      Eve    Finance   73000      4     4.0       LA      F
5    Frank    Finance   68000      6     3.5      NYC      M
6    Grace       Tech   95000      8     4.7  Chicago      F
7     Hank         HR   52000      1     NaN       LA      M
      Name Department   Salary  Years  Rating     City Gender
0    Alice         HR  55000.0    NaN     NaN      NaN    NaN
1      Bob       Tech  82000.0    NaN     NaN      NaN    NaN
2  Charlie       Tech  91000.0    NaN     NaN      NaN    NaN
3    Diana         HR  60000.0    NaN     NaN      NaN    NaN
4      Eve    Finance  73000.0    NaN     NaN      NaN    NaN
5    Frank    Finance  68000.0    NaN     NaN      NaN    NaN
6    Grace       Tech  95000.0    NaN     NaN      NaN    NaN
7     Hank         HR  52000.0    NaN     NaN      NaN    NaN
0      NaN        NaN      NaN    3.0     4.1      NYC      F
1      NaN        NaN      NaN    5.0     3.8       LA      M
2      NaN        NaN      NaN    7.0     4.5      NYC      M
3      NaN        NaN      NaN    2.0     NaN  Chicago      F
4      NaN        NaN      NaN    4.0     4.0       LA      F
5      NaN        NaN      NaN    6.0     3.5      NYC      M
6      NaN        NaN      NaN    8.0     4.7  Chicago      F
7      NaN        NaN      NaN    1.0     NaN       LA      M

'''Yes, in **Pandas** there are several functions similar to **`apply()`** that let you apply functions to data.

Here are the most common ones:

---

## 1️⃣ `apply()`

Applies a function to **rows or columns** of a DataFrame.

```python
df.apply(lambda x: x.max())
```

Example (row-wise):

```python
df.apply(lambda x: x['Salary'] / x['Years'], axis=1)
```

---

## 2️⃣ `map()`

Works on a **single Series (one column)**.

```python
df['Salary'].map(lambda x: x * 1.1)
```

Example:

```python
df['Gender'].map({'M':'Male','F':'Female'})
```

✔ Faster than `apply` for **single column transformations**.

---

## 3️⃣ `applymap()`

Applies a function to **every element of a DataFrame**.

```python
df.applymap(lambda x: str(x).upper())
```

Example:

```python
df.applymap(lambda x: x*2)
```

---

## 4️⃣ `transform()`

Used with **groupby** to transform values while keeping the **same shape**.

Example:

```python
df.groupby('Department')['Salary'].transform('mean')
```

---

## 5️⃣ `agg()` / `aggregate()`

Used for **aggregation operations**.

```python
df.groupby('Department')['Salary'].agg(['mean','max','min'])
```

---

## Quick comparison

| Function      | Works On           | Purpose                      |
| ------------- | ------------------ | ---------------------------- |
| `apply()`     | DataFrame / Series | Apply function row or column |
| `map()`       | Series only        | Transform values             |
| `applymap()`  | Entire DataFrame   | Element-wise operation       |
| `transform()` | GroupBy            | Transform but keep same size |
| `agg()`       | GroupBy / Series   | Aggregation                  |

---

💡 **Simple rule to remember**

```
map → single column
apply → row/column
applymap → entire dataframe
agg → aggregation
transform → groupby transformation
'''

In [60]:
df = pd.read_csv('names.csv',header=0,index_col=0,parse_dates=['Dob'],date_format='%d-%m-%Y')
df2 =pd.DataFrame( df['Dob'])
'''df2["Day"] = df['Dob'].dt.day
df2["Month"] = df['Dob'].dt.month
df2["Year"] = df['Dob'].dt.year'''
df2[['Day','Month','Year']] = df['Dob'].dt.strftime("%d-%m-%y").str.split('-',expand=True)
df2[['Day','Month','Year']] = df['Dob'].apply(
    lambda x : pd.Series([x.day, x.month, x.year])
)
df2.dtypes

Dob      datetime64[us]
Day               int64
Month             int64
Year              int64
dtype: object

In [ ]:
'''resample() is used for time-based grouping in pandas.
It works only when your DataFrame has a DatetimeIndex (or a datetime column set as index).

Think of it like groupby for time periods.
| Code  | Meaning   |
| ----- | --------- |
| `"D"` | Daily     |
| `"W"` | Weekly    |
| `"M"` | Monthly   |
| `"Q"` | Quarterly |
| `"Y"` | Yearly    |
| `"H"` | Hourly    |'''

df.resample("M").sum()