In [1]:
import pandas as pd
import numpy as np

#group by

In [ ]:
df = pd.read_csv('employee.csv',header=0,index_col=0,skipinitialspace=True)
print(df)

df.index.name = 'id' to give the default index name

In [ ]:
col = list(df.columns)
#df.drop('dept',axis = 1,inplace=True)
df.insert(col.index('gender')+1,'dept',np.where(df['salary']==12000,'IT',np.where(df['salary']>12000,'Finance','HR')))
print(df)

In [ ]:
'''print(df.groupby('dept')['salary'].sum())
print(df.groupby('dept')['salary'].mean())
print(df.groupby('dept')['salary'].count())
print(df.groupby('dept')['salary'].min())
print(df.groupby('dept')['salary'].max())'''
print(df.groupby('dept').agg({'salary':{'sum','mean','count','min','max'}}))
print(df.groupby('dept').agg({'salary':'sum','bonus':'sum','age':'mean'}).astype(int))
print(df.groupby('dept')['salary'].agg(['sum','mean','count','min','max']).astype(int))
print(df.groupby('dept')['salary'].agg(avg_sal=('mean'),total_sal='sum',total_emp=('count')).astype(int))

In [ ]:
# transform is used to maintain the shape of the datafram even if we apply groupby it will calculate the groupby object then transform the shape back 
df['dept_avg'] = df.groupby('dept')['salary'].transform('mean')
df['diff'] = df['salary'] - df['dept_avg']
print(df)

In [ ]:
df.drop(['diff','dept_avg'],axis=1,inplace=True)

In [ ]:
df.groupby('dept').filter(lambda x : x['salary'].mean() >= 12000)

In [ ]:
data = pd.read_csv('employee.csv', header=0, index_col=0)
#print(data)
col = list(data.columns)
data.insert(col.index('age')+1,'position',
            np.where(data['age']<20,'intern',
            np.where(data['age']<30,'jr dev',
            np.where(data['age']<40,'sr dev','manager'))))
print(data)

In [50]:
df2 = pd.read_csv('names2.csv',header=0,index_col=0)
print(df2)
df1 = pd.read_csv('names.csv',header=0,index_col=0)
print(df1)

    std     Name
Id
1     6     John
2     7     Anna
3     8    Peter
4     9    Linda
5     5      Tom
6     4     Sara
7     7    David
8     8    Emily
9     9  Michael
10    7   Sophia
       Name  Age         Dob  Marks  Height
Id
1      John   18  23-05-2005     85     170
2      Anna   24  15-08-1999     92     165
3     Peter   35  10-12-1988     78     180
4     Linda   32  05-03-1991     95     160
5       Tom   28  12-11-1993     88     175
6      Sara   22  30-01-2000     90     168
7     David   30  20-07-1992     82     172
8     Emily   27  18-09-1995     89     163
9   Michael   40  25-02-1983     91     185
10   Sophia   26  14-06-1997     87     167

In [52]:
pd.merge(df2,df1,on='Id',how='right')
pd.merge(df2,df1,on='Id',how='left')
pd.merge(df2,df1,left_on = 'Id',right_on='Id')
pd.merge(df1,df2,left_on=['Id','Name'],right_on=['Id','Name'])
df1

       Name  Age         Dob  Marks  Height
Id
1      John   18  23-05-2005     85     170
2      Anna   24  15-08-1999     92     165
3     Peter   35  10-12-1988     78     180
4     Linda   32  05-03-1991     95     160
5       Tom   28  12-11-1993     88     175
6      Sara   22  30-01-2000     90     168
7     David   30  20-07-1992     82     172
8     Emily   27  18-09-1995     89     163
9   Michael   40  25-02-1983     91     185
10   Sophia   26  14-06-1997     87     167

In [ ]:
#df1.rename(columns = {'name':'Name'},inplace=True)

    std     Name
Id
1     6     John
2     7     Anna
3     8    Peter
4     9    Linda
5     5      Tom
6     4     Sara
7     7    David
8     8    Emily
9     9  Michael
10    7   Sophia