In [2]:
import pandas as pd
import numpy as np

Here’s your **clean GitHub Markdown (README-ready)** version 👇

```markdown
## Pandas `rank()` Methods

### Sample Data
```python
import pandas as pd

s = pd.Series([50, 20, 20, 80])
```

---

### Methods Overview

| Method  | Tie Handling | Gaps? | Use Case           | Code Example               |
| ------- | ------------ | ----- | ------------------ | -------------------------- |
| average | mean rank    | ❌     | default            | `s.rank(method='average')` |
| min     | lowest rank  | ✅     | SQL RANK()         | `s.rank(method='min')`     |
| max     | highest rank | ✅     | rare               | `s.rank(method='max')`     |
| first   | order-based  | ❌     | when order matters | `s.rank(method='first')`   |
| dense   | same rank    | ❌     | SQL DENSE_RANK()   | `s.rank(method='dense')`   |

---

### Full Example

```python
import pandas as pd

s = pd.Series([50, 20, 20, 80])

print("average:\n", s.rank(method='average'))
print("min:\n", s.rank(method='min'))
print("max:\n", s.rank(method='max'))
print("first:\n", s.rank(method='first'))
print("dense:\n", s.rank(method='dense'))
```

---

### Output

```
average:
0    3.0
1    1.5
2    1.5
3    4.0

min:
0    3.0
1    1.0
2    1.0
3    4.0

max:
0    3.0
1    2.0
2    2.0
3    4.0

first:
0    3.0
1    1.0
2    2.0
3    4.0

dense:
0    2.0
1    1.0
2    1.0
3    3.0
```

---

### Key Takeaways

- `average` → default behavior  
- `min` → same as SQL `RANK()`  
- `dense` → same as SQL `DENSE_RANK()`  
- `first` → depends on row order  
- `max` → assigns highest rank in ties  
```

In [3]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Hank',
             'Ivy', 'Jack', 'Karen', 'Leo', 'Mia', 'Nate', 'Olivia', 'Paul'],
    'Department':
        ['HR', 'Tech', 'Tech', 'HR', 'Finance', 'Finance', 'Tech', 'HR',
                   'Tech', 'Finance', 'HR', 'Tech', 'Finance', 'HR', 'Tech', 'Finance'],
    'Salary': [55000, 82000, 91000, 60000, 73000, 68000, 95000, 52000,
               87000, 71000, 58000, 99000, 65000, 53000, 78000, 70000],
    'Years': [3, 5, 7, 2, 4, 6, 8, 1, 5, 3, 2, 9, 4, 1, 6, 3],
    'Rating': [4.1, 3.8, 4.5, np.nan, 4.0, 3.5, 4.7, np.nan,
               4.2, 3.9, np.nan, 4.8, 3.6, np.nan, 4.3, 3.7],
    'City': ['NYC', 'LA', 'NYC', 'Chicago', 'LA', 'NYC', 'Chicago', 'LA',
             'NYC', 'Chicago', 'LA', 'NYC', 'Chicago', 'LA', 'NYC', 'Chicago'],
    'Gender': ['F', 'M', 'M', 'F', 'F', 'M', 'F', 'M',
               'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M']
}
df = pd.DataFrame(data)

In [ ]:
'''🟡 Section 1 — Basics & Inspection (Q1–Q6)
Q1. Display the first 5 rows, shape, column names, and data types of df — all in one go.
Q2. How many employees are in each Department? Show the result sorted in descending order.
Q3. Find the total number of missing values per column.
Q4. Get all unique cities in the dataset and the count of employees in each.
Q5. Find the highest and lowest salary in the entire dataset.
Q6. Display basic statistics (mean, std, min, max) for only the numeric columns.'''
print(df.head(5),df.shape,df.columns.tolist(),df.dtypes) #1
print(df['Department'].value_counts())#2
print(df.isnull().sum().sum())#2
print(df['City'].unique().tolist())#4
print(df.select_dtypes(include=['number']).agg(['mean','sum','std','min','max']))#5

      Name Department  Salary  Years  Rating     City Gender
0    Alice         HR   55000      3     4.1      NYC      F
1      Bob       Tech   82000      5     3.8       LA      M
2  Charlie       Tech   91000      7     4.5      NYC      M
3    Diana         HR   60000      2     NaN  Chicago      F
4      Eve    Finance   73000      4     4.0       LA      F (16, 7) ['Name', 'Department', 'Salary', 'Years', 'Rating', 'City', 'Gender'] Name              str
Department        str
Salary          int64
Years           int64
Rating        float64
City              str
Gender            str
dtype: object
Department
Tech       6
HR         5
Finance    5
Name: count, dtype: int64
4
['NYC', 'LA', 'Chicago']
            Salary      Years     Rating
mean  7.231250e+04   4.312500   4.091667
sum   1.157000e+06  69.000000  49.100000
std   1.514252e+04   2.414367   0.423102
min   5.200000e+04   1.000000   3.500000
max   9.900000e+04   9.000000   4.800000

In [ ]:
'''
🟠 Section 2 — Filtering & Indexing (Q7–Q13)
Q7. Filter employees from the Tech department earning more than 85,000.
Q8. Get all employees from NYC or Chicago who have a Rating above 4.0.
Q9. Select employees whose name starts with the letter 'A', 'B', or 'C'.
Q10. Find employees who are in Finance and have worked for less than 4 years.
Q11. Use .loc[] to select rows where Years is between 3 and 6 (inclusive), and show only Name, Department, Salary.
Q12. Use .iloc[] to select the last 5 rows and the first 3 columns.
Q13. Find all employees whose Salary is above the overall mean salary.'''
print(df[(df['Department']=='Tech')&(df['Salary']>85000)])#1
print(df[df['City'].isin(['NYC','Chicago'])&(df['Rating']>4.0)])#2
print(df[df['Name'].str.startswith(('A','B','C'))])#3
print(df[(df['Department'] == 'Finance') & (df['Years'] < 4)])#4
print(df.loc[df['Years'].between(3,6),['Name','Department','Salary',]])#5
print(df.iloc[-5:,:3])#6
print(df.loc[df['Salary']>df['Salary'].mean()])#7

       Name Department  Salary  Years  Rating     City Gender
2   Charlie       Tech   91000      7     4.5      NYC      M
6     Grace       Tech   95000      8     4.7  Chicago      F
8       Ivy       Tech   87000      5     4.2      NYC      F
11      Leo       Tech   99000      9     4.8      NYC      M
       Name Department  Salary  Years  Rating     City Gender
0     Alice         HR   55000      3     4.1      NYC      F
2   Charlie       Tech   91000      7     4.5      NYC      M
6     Grace       Tech   95000      8     4.7  Chicago      F
8       Ivy       Tech   87000      5     4.2      NYC      F
11      Leo       Tech   99000      9     4.8      NYC      M
14   Olivia       Tech   78000      6     4.3      NYC      F
      Name Department  Salary  Years  Rating City Gender
0    Alice         HR   55000      3     4.1  NYC      F
1      Bob       Tech   82000      5     3.8   LA      M
2  Charlie       Tech   91000      7     4.5  NYC      M
    Name Department  Salary  Years  Rating     City Gender
9   Jack    Finance   71000      3     3.9  Chicago      M
15  Paul    Finance   70000      3     3.7  Chicago      M
      Name Department  Salary
0    Alice         HR   55000
1      Bob       Tech   82000
4      Eve    Finance   73000
5    Frank    Finance   68000
8      Ivy       Tech   87000
9     Jack    Finance   71000
12     Mia    Finance   65000
14  Olivia       Tech   78000
15    Paul    Finance   70000
      Name Department  Salary
11     Leo       Tech   99000
12     Mia    Finance   65000
13    Nate         HR   53000
14  Olivia       Tech   78000
15    Paul    Finance   70000
       Name Department  Salary  Years  Rating     City Gender
1       Bob       Tech   82000      5     3.8       LA      M
2   Charlie       Tech   91000      7     4.5      NYC      M
4       Eve    Finance   73000      4     4.0       LA      F
6     Grace       Tech   95000      8     4.7  Chicago      F
8       Ivy       Tech   87000      5     4.2      NYC      F
11      Leo       Tech   99000      9     4.8      NYC      M
14   Olivia       Tech   78000      6     4.3      NYC      F

In [ ]:
'''🔵 Section 3 — Cleaning & Transformation (Q14–Q20)
Q14. Fill missing Rating values with the median rating (without modifying the original df).
Q15. Drop all rows where Rating is missing.
Q16. Create a new column "Experience_Level" with values:
"Junior" → Years < 3
"Mid" → 3 ≤ Years ≤ 6
"Senior" → Years > 6
Q17. Rename the columns Salary → Annual_Salary and Years → Experience_Years.
Q18. Convert the Gender column from 'M'/'F' to 'Male'/'Female' using .map().
Q19. Create a "Salary_Band" column using pd.cut() with 3 equal-width bands labeled "Low", "Medium", "High".
Q20. Reset the index of df after dropping rows where Rating is null. Make sure the old index is not kept as a column.'''
df['Rating'].fillna(df['Rating'].median())#1
df.dropna(subset=['Rating'])#2
data=np.select([df['Years']<3,df['Years']>6],['Junior','Senior'],default='Mid')#3
df['Experience_Level'] = data
df.rename(columns={'Salary':'Annual_Salary','Years':'Experience_Years'},inplace=True) #4
df['Gender'] = df['Gender'].map({'M': 'Male', 'F': 'Female'}) #5
df['Salary_Band'] = pd.cut(df['Annual_Salary'],bins=3,labels=['Low', 'Medium', 'High'])#6 
'''Range = Max - Min = 120,000 - 40,000 = 80,000

### Step 2 — It divides into 3 **equal-width** bins
```
Bin 1 "Low"    → 40,000  to  66,666
Bin 2 "Medium" → 66,667  to  93,333
Bin 3 "High"   → 93,334  to 120,000
```
> 💡 Each bin covers the **same salary range (≈26,666)** — that's what *equal-width* means.

### Step 3 — It assigns a label to every employee
```
Employee A → Salary 45,000  → "Low"
Employee B → Salary 75,000  → "Medium"
Employee C → Salary 110,000 → "High"'''
df = df.dropna(subset=['Rating']).reset_index(drop=True) #7

In [25]:
'''🔴 Section 4 — GroupBy & Aggregation (Q21–Q27)
Q21. Find the mean salary grouped by `Department`.
Q22. For each `Department`, find the total salary expenditure and number of employees.
Q23. Group by `Department` and `City`, and find the average rating for each combination.
Q24. Find the top earner (Name + Salary) in each department. (Hint: `idxmax`)
Q25. How many `Male` and `Female` employees are there in each `Department`?
Q26. Use `.agg()` to compute min, max, and mean of `Salary` grouped by `Department`.
Q27. Find departments where the average salary is above 75,000.'''
df.groupby('Department').agg({'Salary': 'sum'})
df.groupby('Department').agg({'Salary': ['sum','count']})
df.groupby(['Department','City'])['Rating'].mean()
df.groupby(['Department','Gender']).size()
df.groupby(['Department']).agg({'Salary': ['mean','min','max']})
df.groupby(['Department'])['Salary'].mean()[lambda x : x>75000]

Department
Tech    88666.666667
Name: Salary, dtype: float64

In [10]:
reviews = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Eve', 'Grace', 'Leo','Riya'],
    'Review': ['Good', 'Average', 'Excellent', 'Good', 'Excellent', 'Good','Excellent']
})
dept_budget = pd.DataFrame({
    'Department': ['HR', 'Tech', 'Finance'],
    'Budget': [200000, 500000, 350000]
})

In [47]:
'''Q33. Merge df with reviews so all employees are kept and those without a review show NaN.
Q34. Merge df with reviews and keep only employees who have a review (inner join).
Q35. Merge df with dept_budget on Department so each employee also shows their department's budget.
Q36. After merging df with dept_budget, create a column "Salary_to_Budget_Ratio" = Salary / Budget.
'''
pd.merge(df,reviews,on='Name',how='left')
pd.merge(df,reviews,on='Name',how='inner')
pd.merge(df,dept_budget,on='Department')
merged = pd.merge(df,dept_budget,on='Department').assign(Salary_to_Budget_Ratio =lambda x : x['Salary']/x['Budget'])
merged

,Name,Department,Salary,Years,Rating,City,Gender,Budget,Salary_to_Budget_Ratio
0,Alice,HR,55000,3,4.1,NYC,F,200000,0.275000
1,Bob,Tech,82000,5,3.8,LA,M,500000,0.164000
2,Charlie,Tech,91000,7,4.5,NYC,M,500000,0.182000
3,Diana,HR,60000,2,NaN,Chicago,F,200000,0.300000
4,Eve,Finance,73000,4,4.0,LA,F,350000,0.208571
5,Frank,Finance,68000,6,3.5,NYC,M,350000,0.194286
6,Grace,Tech,95000,8,4.7,Chicago,F,500000,0.190000
7,Hank,HR,52000,1,NaN,LA,M,200000,0.260000
8,Ivy,Tech,87000,5,4.2,NYC,F,500000,0.174000
9,Jack,Finance,71000,3,3.9,Chicago,M,350000,0.202857
10,Karen,HR,58000,2,NaN,LA,F,200000,0.290000
11,Leo,Tech,99000,9,4.8,NYC,M,500000,0.198000
12,Mia,Finance,65000,4,3.6,Chicago,F,350000,0.185714
13,Nate,HR,53000,1,NaN,LA,M,200000,0.265000
14,Olivia,Tech,78000,6,4.3,NYC,F,500000,0.156000
15,Paul,Finance,70000,3,3.7,Chicago,M,350000,0.200000

In [35]:
'''⚫ Section 7 — Reshaping & Pivot Tables (Q37–Q40)
Q37. Create a pivot_table showing the mean salary for each Department × City combination.
Q38. Create a pivot_table showing mean Rating and mean Salary per Department.
Q39. Use pd.melt() to unpivot the df so that Salary, Years, and Rating become rows under a "Variable" and "Value" column, keeping Name and Department as identifiers.
Q40. Sort the full DataFrame by Department (ascending) and then by Salary (descending) within each department. Display the result.'''
df.pivot_table(index='Department',columns ='City',values = 'Salary',aggfunc='mean').round(2)
df.pivot_table(index='Department',values=['Salary','Rating'],aggfunc='mean').astype(int)
df.melt(id_vars=['Name','Department'],value_vars=['Salary','Years','Rating'],var_name = 'Variable',value_name = 'Value')
df.sort_values(by=['Department','Salary'],ascending=[True,False])

       Name Department  Salary  Years  Rating     City Gender
4       Eve    Finance   73000      4     4.0       LA      F
9      Jack    Finance   71000      3     3.9  Chicago      M
15     Paul    Finance   70000      3     3.7  Chicago      M
5     Frank    Finance   68000      6     3.5      NYC      M
12      Mia    Finance   65000      4     3.6  Chicago      F
3     Diana         HR   60000      2     NaN  Chicago      F
10    Karen         HR   58000      2     NaN       LA      F
0     Alice         HR   55000      3     4.1      NYC      F
13     Nate         HR   53000      1     NaN       LA      M
7      Hank         HR   52000      1     NaN       LA      M
11      Leo       Tech   99000      9     4.8      NYC      M
6     Grace       Tech   95000      8     4.7  Chicago      F
2   Charlie       Tech   91000      7     4.5      NYC      M
8       Ivy       Tech   87000      5     4.2      NYC      F
1       Bob       Tech   82000      5     3.8       LA      M
14   Olivia       Tech   78000      6     4.3      NYC      F

In [11]:
df.merge(reviews,on ='Name',how = 'outer',indicator='Source')

,Name,Department,Salary,Years,Rating,City,Gender,Review,Source
0,Alice,HR,55000.0,3.0,4.1,NYC,F,Good,both
1,Bob,Tech,82000.0,5.0,3.8,LA,M,Average,both
2,Charlie,Tech,91000.0,7.0,4.5,NYC,M,Excellent,both
3,Diana,HR,60000.0,2.0,NaN,Chicago,F,NaN,left_only
4,Eve,Finance,73000.0,4.0,4.0,LA,F,Good,both
5,Frank,Finance,68000.0,6.0,3.5,NYC,M,NaN,left_only
6,Grace,Tech,95000.0,8.0,4.7,Chicago,F,Excellent,both
7,Hank,HR,52000.0,1.0,NaN,LA,M,NaN,left_only
8,Ivy,Tech,87000.0,5.0,4.2,NYC,F,NaN,left_only
9,Jack,Finance,71000.0,3.0,3.9,Chicago,M,NaN,left_only
10,Karen,HR,58000.0,2.0,NaN,LA,F,NaN,left_only
11,Leo,Tech,99000.0,9.0,4.8,NYC,M,Good,both
12,Mia,Finance,65000.0,4.0,3.6,Chicago,F,NaN,left_only
13,Nate,HR,53000.0,1.0,NaN,LA,M,NaN,left_only
14,Olivia,Tech,78000.0,6.0,4.3,NYC,F,NaN,left_only
15,Paul,Finance,70000.0,3.0,3.7,Chicago,M,NaN,left_only
16,Riya,NaN,NaN,NaN,NaN,NaN,NaN,Excellent,right_only